branches:
  only:
  - python
language: python
python:
- pypy
- pypy3
- 2.6
- 2.7
- 3.3
- 3.4
install:
- pip install -e . "Werkzeug >= 0.9" coverage coveralls
script:
- coverage run --source sass,sassc,sassutils setup.py test
after_success:
- coveralls
